<?php

namespace App\Notifications;

use App\Models\User;
use App\Models\Flight;
use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;

class AdminOrderConfirmation extends Notification
{
    use Queueable;

    /**
     * Create a new notification instance.
     */
    public $user_id;
    public $flight_id;

    public function __construct($user_id, $flight_id)
    {
        //
        $this->user_id = $user_id;
        $this->flight_id = $flight_id;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @return array<int, string>
     */
    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    /**
     * Get the mail representation of the notification.
     */
    public function toMail(object $notifiable): MailMessage
    {
        $user = User::find($this->user_id);
        $flight = Flight::find($this->flight_id);

        return (new MailMessage)
                    ->line(ucfirst($user->name) . ', You have received a new ticket purchase for flight:')
                    ->line($flight->origin . ' / ' . $flight->destination)
                    ->line('Date: ' . $flight->date->format('d-m-Y'))
                    ->line('please review the details of all passengers at the following link.')
                    ->action('Flight Passengers', url('/flights/' . $flight->id . '/passengers'))
                    ->line('This email was automatically generated by the administrative system of Universal Airlines.');
    }
}
